services:
  web:
    build:
      context: /home/azureuser/app           # 프로젝트 루트
      dockerfile: docker/Dockerfile          # docker 폴더 안의 Dockerfile
    container_name: paju_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - /home/azureuser/app:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - /home/azureuser/app/.env

volumes:
  static_volume:
  media_volume: