services:
  web:
    build:
      context: ../..        # 프로젝트 루트
      dockerfile: docker/Dockerfile
    container_name: paju_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../../:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - /home/azureuser/app/.env 
    environment:
      - DB_HOST=${DB_HOST:-host.docker.internal}   # 기본값 host.docker.internal
      - DB_PORT=${DB_PORT:-3306}

volumes:
  static_volume:
  media_volume: