name: Deploy

on:
  push:
    branches: [ feat/api ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build & Push
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/paju_web:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/paju_web:latest

    - name: Deploy to Server
      env:
        DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
        DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
        DEPLOY_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
        ENV_AZURE: ${{ secrets.AZURE_SETTINGS }}
        ENV_DB: ${{ secrets.DB_SETTINGS }}
        DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/paju_web:latest

      run: |
        mkdir -p ~/.ssh
        echo "$DEPLOY_KEY" > ~/.ssh/key
        chmod 600 ~/.ssh/key
        ssh-keyscan -H $DEPLOY_HOST >> ~/.ssh/known_hosts

        # deploy.sh 서버로 전송
        scp -i ~/.ssh/key deploy.sh $DEPLOY_USER@$DEPLOY_HOST:/home/azureuser/deploy.sh

        # 서버에서 실행
        ssh -i ~/.ssh/key $DEPLOY_USER@$DEPLOY_HOST \
          "ENV_AZURE='$ENV_AZURE' ENV_DB='$ENV_DB' bash /home/azureuser/deploy.sh $DOCKER_IMAGE"